const reviews = [
    {
        id: 1,
        name: "Jessica Moreland",
        review: "He went above and beyond in helping me and did a great job!! I will be working with him again in the future and couldn’t be more happy with my results!!!",
        country: "🇬🇧🇺🇸 United State",
        platform: "Fiverr",
    },
    {
        id: 2,
        name: "shorthills",
        review: "He is willing to improve and learn. You can get delivery as per you need. Thanks Amir",
        country: "🇬🇧🇺🇸🇨🇦🇱🇹🇨🇲🇫🇷🇮🇳 India",
        platform: "Fiverr",
    },
    {
        id: 3,
        name: "alexandrenivess",
        review: "Great help in getting our SEO optimised. I highly recommend !",
        country: "🇬🇧🇺🇸🇨🇦🇱🇹🇨🇲🇫🇷 France",
        platform: "Fiverr",
    },
    {
        id: 4,
        name: "nguite",
        review: "Amir doesn't just sell the service he provides; he equally sells the service. You are really professional my friends. Thanks for the personal involvement you had in my work. We shall continue to work together.",
        country: "🇬🇧🇺🇸🇨🇦🇱🇹🇨🇲 Cameroon",
        platform: "Fiverr",
    },
    {
        id: 5,
        name: "jagkhaira",
        review: "The seller needed minimal instructions and completed all tasks to a high standard. I am very pleased with the final delivery.",
        country: "🇬🇧United Kingdom",
        platform: "Fiverr",
    },
    {
        id: 6,
        name: "milana",
        review: "Developer done good work, done it very fast.",
        country: "🇬🇧🇺🇸🇨🇦🇱🇹 Lithuania",
        platform: "Fiverr",
    },
    {
        id: 7,
        name: "dmshouston",
        review: "Amir has been working hard on our projects and followed all the instructions accordingly. Has good working knowledge and ideas.Very recommended freelancer!",
        country: "🇬🇧🇺🇸 United States",
        platform: "Fiverr",
    },
    {
        id: 8,
        name: "dmshouston",
        review: "Awesome Provider! highly recommended and would like to cooperate more. Thank you!",
        country: "🇬🇧🇺🇸 United States",
        platform: "Fiverr",
    },
    {
        id: 9,
        name: "randyredman",
        review: "Wonderful service did wha the said he would do - will rose again - great at making revisions too",
        country: "🇬🇧🇺🇸 United States",
        platform: "Fiverr",
    },
    {
        id: 10,
        name: "jagkhaira",
        review: "Great Quality of work. Happy with what the seller brought to this project in terms of creativity.",
        country: "🇬🇧 United Kingdom",
        platform: "Fiverr",
    },
    {
        id: 11,
        name: "malikomar",
        review: "Professional and efficient! Would recommend to anyone! Very knowledgeable expert!!! Regards, Omar M.",
        country: "🇬🇧🇺🇸🇨🇦 Canada",
        platform: "Fiverr",
    },
    {
        id: 12,
        name: "Aimee",
        review: "Mostafa is highly professional, he works fast and goes above and beyond to get you what you are looking for. Exceptional service and hard working. I have worked with many people and he has been by far the easiest to communicate with and the most reliable. I highly recommend working with Mostafa, and I will certainly be working with him down the track. It has been a pleasure to have my website built by you, and I look forward to much more success and projects with Mostafa. Thanks so much Mostafa!",
        country: "🇬🇧🇺🇸🇨🇦🇱🇹🇨🇲🇫🇷 France",
        platform: "Upwork",
    },
    {
        id: 13,
        name: "Kevin Okah N",
        review: "The very first project I asked Mostafa M. to do for me was a marvelous experience for me. He doesn't only think about the financial part of the project but actually makes you the client feel you are the KING when it comes to doing business. Very good communication and prompt response. There is no way I would have any other person do my work if it is not Mostafa M. Well done sir",
        country: "🇬🇧 United Kingdom",
        platform: "Upwork",
    }
]
export default reviews;